name = input("Enter Employee Name :")
role = input("Enter Employee Role :")
salary = float(input("Enter Monthly Salary :"))

print("==============================")
print("-----EMPLOYEE ID CARD-----")
print("==============================")
print("Name",name)
print("Role",role)
print("Salary",salary)
